<x-app title="Sejarah">
  <div class="container px-4 m-auto mb-10">
    <h1 class="py-10 text-4xl">Sejarah</h1>
    <div class="font-lg leading-7">
      <p class="mt-4">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae voluptate sapiente labore magni numquam excepturi impedit nisi, eligendi fugiat dolorem ad aliquam atque cupiditate repellendus facilis soluta molestiae, doloribus quidem alias error. Voluptatem nam quo maxime deleniti harum a ea aperiam suscipit, maiores quas voluptate totam ratione assumenda quam perferendis modi recusandae tempore. Libero autem aperiam velit culpa provident iste? Rerum corrupti, at cupiditate esse quae quidem minus dolorum qui nesciunt enim? Saepe quis neque inventore eos ullam soluta totam consectetur consequuntur, perferendis quam. Delectus, quasi? Veniam deserunt, voluptas necessitatibus voluptate, vitae in laborum reiciendis praesentium libero consequuntur fugit vero.
      </p>
      <p class="mt-4">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae voluptate sapiente labore magni numquam excepturi impedit nisi, eligendi fugiat dolorem ad aliquam atque cupiditate repellendus facilis soluta molestiae, doloribus quidem alias error. Voluptatem nam quo maxime deleniti harum a ea aperiam suscipit, maiores quas voluptate totam ratione assumenda quam perferendis modi recusandae tempore. Libero autem aperiam velit culpa provident iste? Rerum corrupti, at cupiditate esse quae quidem minus dolorum qui nesciunt enim? Saepe quis neque inventore eos ullam soluta totam consectetur consequuntur, perferendis quam. Delectus, quasi? Veniam deserunt, voluptas necessitatibus voluptate, vitae in laborum reiciendis praesentium libero consequuntur fugit vero.
      </p>
      <p class="mt-4">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae voluptate sapiente labore magni numquam excepturi impedit nisi, eligendi fugiat dolorem ad aliquam atque cupiditate repellendus facilis soluta molestiae, doloribus quidem alias error. Voluptatem nam quo maxime deleniti harum a ea aperiam suscipit, maiores quas voluptate totam ratione assumenda quam perferendis modi recusandae tempore. Libero autem aperiam velit culpa provident iste? Rerum corrupti, at cupiditate esse quae quidem minus dolorum qui nesciunt enim? Saepe quis neque inventore eos ullam soluta totam consectetur consequuntur, perferendis quam. Delectus, quasi? Veniam deserunt, voluptas necessitatibus voluptate, vitae in laborum reiciendis praesentium libero consequuntur fugit vero.
      </p>
      <p class="mt-4">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos quis, dolorem praesentium accusamus veniam suscipit velit. Quod totam nostrum, odio impedit eos veniam amet aliquam? Voluptas enim dolor libero cum asperiores obcaecati sequi modi cupiditate explicabo consequatur esse maiores voluptatum natus, fugit ab eos aut quibusdam totam quia neque ipsam. Itaque nostrum cum culpa numquam? Aperiam, repellat fugiat incidunt eum vero asperiores ut ipsa hic et. Provident nulla, maiores temporibus ipsa nemo numquam esse nostrum error minus illum atque reprehenderit culpa impedit, dolorum alias inventore quia maxime laudantium tempore. Assumenda ab cum at ratione animi commodi perspiciatis minima molestiae! Eaque, atque nesciunt facere repudiandae natus accusantium molestiae fugit temporibus id at voluptate, ea in praesentium iusto obcaecati maxime aperiam quae a ratione sapiente unde earum. Explicabo, tempore. Eaque eligendi, officia praesentium repellendus asperiores voluptas, numquam iusto officiis vitae rerum assumenda dolores laboriosam libero! Corrupti cumque dolorum eaque exercitationem neque tenetur dolore recusandae magnam ea consequatur hic impedit aperiam rerum tempore autem, quaerat obcaecati sequi asperiores quod accusamus, totam qui ad assumenda! Placeat repellat maiores inventore accusamus at dolore voluptates fugiat quas cumque pariatur sint esse, deleniti libero et eos laborum modi, excepturi unde aperiam nostrum, harum voluptas. Autem, modi totam.
      </p>
    </div>
  </div>
</x-app>
